accounts/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('sign_up', views.sign_up, name='sign_up'),
    path('log_in', views.log_in,name='log_in'),
    path('log_out', views.log_out,name='log_out'), 
    path('profile', views.profile, name='profile'),
    path('editaccount/<id>', views.editaccount, name='editaccount'),
    path('deleteaccount/<id>', views.deleteaccount, name='deleteaccount'),
]

backend/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('', views.index, name='index'),
    path('roster', views.roster, name='roster'),
    path('about', views.about, name='about'),

###post_section
    path('createpost', views.createpost, name='createpost'),
    path('postdetail/<id>', views.postdetail, name='postdetail'),
    path('editpost/<id>', views.editpost, name='editpost'),
    path('deletepost/<id>', views.deletepost, name='deletepost'),

###event_section
    path('addevent',views.addevent, name='addevent'),
    path('eventdetail/<id>',views.eventdetail, name='eventdetail'),
    path('editevent/<id>',views.editevent, name='editevent'),
    path('deleteevent/<id>',views.deleteevent, name='deleteevent'),
    path('eventsignup/<id>',views.event_signup, name='event_signup'),
    path('eventcalendar', views.event_calendar.as_view(), name='event_calendar'),
]

css_website/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path

urlpatterns = [
    path('', include(('backend.urls','backend'), namespace='backend')),
    path('accounts/', include(('accounts.urls','accounts'), namespace='accounts')),
    path('admin/', admin.site.urls),
]

accounts/models.py
from django.db import models

from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)


class MyUserManager(BaseUserManager):
    def create_user(self, email, date_of_birth, first_name, last_name, year, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            date_of_birth=date_of_birth,
            first_name=first_name,
            last_name=last_name,
            year=year,
            password=password
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, date_of_birth, first_name, last_name, year, password=None):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email,
            date_of_birth=date_of_birth,
            first_name=first_name,
            last_name=last_name,
            year=year,
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser):
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    first_name=models.CharField(max_length=100)
    last_name=models.CharField(max_length=100)
    date_of_birth = models.DateField()
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    FRESHMAN = 'FR'
    SOPHOMORE = 'SO'
    JUNIOR = 'JR'
    SENIOR = 'SR'
    GRADUATE = 'GR'
    year_in_school= [
        (FRESHMAN, 'Freshman'),
        (SOPHOMORE, 'Sophomore'),
        (JUNIOR, 'Junior'),
        (SENIOR, 'Senior'),
        (GRADUATE, 'Graduate'),
    ]
    year = models.CharField(
        max_length=2,
        choices=year_in_school,
        default="FR"
    )

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['date_of_birth', 'first_name', 'last_name', 'year']

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

accounts/forms.py
from django.forms import ModelForm,TextInput, DateInput
from django.forms.widgets import PasswordInput
from accounts.models import MyUser
from django import forms
from django.contrib.auth.forms import UserCreationForm
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

class SignUpForm(UserCreationForm):

    class Meta:
        model = MyUser
        password1= forms.CharField(label='Password')
        password2= forms.CharField(label='Repeat Password')
        fields = ('email', 'date_of_birth', 'first_name', 'last_name', 'year')
        widgets = {
            'email': TextInput(attrs={'placeholder': '*****@abc.com'}),
            'date_of_birth': DateInput(attrs={'placeholder': 'YYYY-MM-DD'}),
            'first_name': TextInput(attrs={'placeholder': 'Your Name'}),
            'last_name': TextInput(attrs={'placeholder': 'Your last Name'}),
            'password1':PasswordInput,
            'password2':PasswordInput,
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Submit'))
    

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from accounts.forms import SignUpForm
from django.contrib.auth.decorators import login_required
from backend.models import Post, Event 
from accounts.models import MyUser
from django.urls import reverse

def sign_up(request):
    if request.method=='POST':
        form=SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:log_in')
    else:
        form=SignUpForm()
    return render(request, 'accounts/signup.html', {'form':form})

def log_in(request):
    if request.method=="POST":
        email=request.POST.get('email')
        password=request.POST.get('password')
        user=authenticate(request, email=email, password=password)
        if user is not None:
            login(request, user)
            return redirect('backend:index') 
        else:
            return render(request, 'accounts/login.html', {'message':"Invalid Credentials. Please try again."}) 
    return render(request, 'accounts/login.html')

def log_out(request):
    logout(request)
    return redirect('backend:index')

@login_required(login_url='accounts/login/')
def profile(request):
    user=request.user
    posts=Post.objects.filter(author_id__email=user.email)
    context={
        'posts':posts,
        'user':user
    }
    return render(request, 'accounts/profile.html', context)

@login_required(login_url='accounts/login/')
def editaccount(request, id):
    user=get_object_or_404(MyUser,id=id)
    form=SignUpForm(request.POST or None, instance=user)

    if form.is_valid():
        form.save()
        return redirect(reverse('accounts:profile', kwargs={"id":id}))
    return render(request, 'accounts/editaccount.html', {'form':form})

@login_required(login_url='accounts/login/')
def deleteaccount(request, id):
    user=get_object_or_404(MyUser,id=id)
    user.delete()
    return render(request, 'backend/index.html')

accounts/templates/accounts/editaccount.html
{%extends 'backend/base.html' %}

{% block title %}Edit Account {%endblock%}

{% block content %}
       
<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Update">
  </form>

{%endblock%}

accounts/templates/accounts/login.html
{% extends 'backend/base.html' %}
{% block title %}Login{% endblock %}
{% block content %}

<div id="login_form" class="loginsignup_form">

  {% if message %}

  <div class="alert alert-danger">
    {{ message }}
</div>


{% endif %}
  <form class="login_form" action="{% url 'accounts:log_in' %}"  method="POST">
    {% csrf_token %}

    <div class="form-group"> 
        <h1 class="h3 mb-3 font-weight-normal" style="text-align: center"> Login</h1>
    </div>

    <div class="form-group">
        <input type="email" id="inputEmail" class="form-control" placeholder="Email address" name='email' required autofocus="">
    </div>

    <div class="form-group">
      <input type="password" id="inputPassword" class="form-control" placeholder="Password" name='password' required>
      
    </div>
      
      
     <div class="form-group">
        <button class="btn btn-success btn-block" type="submit"><span class="glyphicon glyphicon-log-in"> Login</button>
      </div>

  
        <a href="#" id="forgot_pswd">Forgot password?</a>
      
      
</div>


{%endblock %}

accounts/templates/accounts/profile.html
{% extends 'backend/base.html' %}
{% block title %}{{user.first_name}}:Profile {% endblock %}

{% block content %}



{% if posts %}
            {% for post in posts %}


            <div class="card">
                <div class="card-header">
                    <h2><a href="{% url 'backend:postdetail' post.id %}">{{post.post_title}}</a></h2>
                    <p class="card-title"><i class="fa fa-user"></i> by <a href="{%url 'accounts:profile' %}">{{post.author_id.first_name}}</a>
                        <i class="fa fa-calendar"></i> Posted on {{post.pub_date}} </p>
                </div>
                <div class="card-body">
                  
                  <p class="card-text">{{post.post_content}}</p>
                </div>
              </div>
              <li><a href="{% url 'accounts:editaccount' user.id %}">Edit Account</a>
                <li> <a href="{% url 'accounts:deleteaccount' user.id %}">Delete Account</a></li> 
            {% endfor %}
          


        {% else %}
            no posts.
        {% endif %}
    
           

{% endblock %}

accounts/templates/accounts/signup.html
{%extends 'backend/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <form action="{% url 'accounts:sign_up' %}" method="POST">
      {% csrf_token %}
        {% crispy form %}
    </form>
{%endblock%}