accounts/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('sign_up', views.sign_up, name='sign_up'),
    path('log_in', views.log_in,name='log_in'),
    path('log_out', views.log_out,name='log_out'), 
    path('profile', views.profile, name='profile'),
    path('editaccount/<id>', views.editaccount, name='editaccount'),
    path('deleteaccount/<id>', views.deleteaccount, name='deleteaccount'),
]

backend/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('', views.index, name='index'),
    path('roster', views.roster, name='roster'),
    path('about', views.about, name='about'),

###post_section
    path('createpost', views.createpost, name='createpost'),
    path('postdetail/<id>', views.postdetail, name='postdetail'),
    path('editpost/<id>', views.editpost, name='editpost'),
    path('deletepost/<id>', views.deletepost, name='deletepost'),

###event_section
    path('addevent',views.addevent, name='addevent'),
    path('eventdetail/<id>',views.eventdetail, name='eventdetail'),
    path('editevent/<id>',views.editevent, name='editevent'),
    path('deleteevent/<id>',views.deleteevent, name='deleteevent'),
    path('eventsignup/<id>',views.event_signup, name='event_signup'),
    path('eventcalendar', views.event_calendar.as_view(), name='event_calendar'),
]

css_website/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path

urlpatterns = [
    path('', include(('backend.urls','backend'), namespace='backend')),
    path('accounts/', include(('accounts.urls','accounts'), namespace='accounts')),
    path('admin/', admin.site.urls),
]

backend/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings

class Post(models.Model):
    post_title=models.CharField(max_length=100)
    post_content=models.TextField()
    pub_date=models.DateTimeField()
    author_id=models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.post_title}--{self.pub_date}--{self.author_id}"


class Event(models.Model):
    event_title=models.CharField(max_length=100)
    event_description=models.TextField()
    start_time=models.DateTimeField()
    end_time=models.DateTimeField()

    def __str__(self):
        return f"{self.event_title}--{self.event_description}--{self.start_time}--{self.start_time}"

    # def check_overlap(self, original_start, original_end, new_start, new_end):
    #     overlap=False
    #     if new_start==original_end or new_end==original_start:
    #         overlap=False
    #     elif(new_start>=original_start and new_start<=original_end) or (new_end>=original_start and new_end<=original_end):
    #         overlap=True
    #     elif new_start<=original_start and new_end>=original_end:
    #         overlap=True

backend/forms.py
from django.forms import ModelForm, DateInput
from backend.models import Event, Post

class PostForm(ModelForm):
    class Meta:
        model=Post
        fields=['post_title', 'post_content', 'pub_date', 'author_id']

class EventForm(ModelForm):
    class Meta:
        model=Event
        widgets={
            'start_time':DateInput(format='%Y-%m-%dT%H:%M',  attrs={'placeholder':'Select a date', 'type':'datetime-local'}),
            'end_time':DateInput(format='%Y-%m-%dT%H:%M',  attrs={'placeholder':'Select a date', 'type':'datetime-local'}),
        }
        fields = '__all__'

backend/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import Http404
from .models import Post, Event
from accounts.models import MyUser
from backend.forms import PostForm, EventForm
from datetime import datetime, date, timedelta
from django.views import generic
from django.utils.safestring import mark_safe
from backend.calendar import Calendar
import calendar
# Create your views here.

def index(request):
    try: 
        allposts=Post.objects.all()
    except Post.DoesNotExist: 
        raise Http404("Post does not exist")
    
    return render(request, "backend/index.html", {"posts":allposts})
    

def roster(request):
    try:
       allusers=MyUser.objects.all()
    except MyUser.DoesNotExist: 
        raise Http404("User does not exist")
    
    return render(request, "backend/roster.html", {"users":allusers})
    
def event_signup(request):
   pass

@login_required(login_url='accounts/login/')
def createpost(request):
    if request.method=='POST':
        form=PostForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('backend:index')
    else:
        form=PostForm()
    return render(request, 'backend/newpost.html', {'form':form})

@login_required(login_url='accounts/login/')
def postdetail(request, id):
    context={
        'post':Post.objects.get(id=id)
    }
    return render(request, 'backend/postdetail.html', context)

@login_required(login_url='accounts/login/')
def editpost(request, id):
    post=get_object_or_404(Post,id=id)
    form=PostForm(request.POST or None, instance=post)

    if form.is_valid():
        form.save()
        return redirect(reverse('backend:postdetail', kwargs={"id":id}))
    return render(request, 'backend/editpost.html', {'form':form})

@login_required(login_url='accounts/login/')
def deletepost(request, id):
    post=get_object_or_404(Post,id=id)
    post.delete()
    return render(request, 'backend/index.html')

def about(request):
   return render(request, 'backend/about.html')


class event_calendar(generic.ListView):
    model=Event
    template_name='backend/event_calendar.html'

    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)

        d=get_date(self.request.GET.get('month', None))

        cal=Calendar(d.year, d.month)

        html_cal=cal.formatmonth(withyear=True)
        context['calendar']=mark_safe(html_cal)
        context['prev_month']=prev_month(d)
        context['next_month']=next_month(d)
        return context
    
def get_date(req_month):
    if req_month:
        year,month=(int(x) for x in req_month.split('-'))
        return date(year, month, day=1)
    return datetime.today()    

def prev_month(d):
    first=d.replace(day=1)
    prev_month=first-timedelta(days=1)
    month='month='+str(prev_month.year)+'-'+str(prev_month.month)
    return month

def next_month(d):
    days_in_month=calendar.monthrange(d.year, d.month)[1]
    last=d.replace(day=days_in_month)
    next_month=last+timedelta(days=1)
    month='month='+str(next_month.year)+'-'+str(next_month.month)
    return month

def addevent(request):
    if request.method=='POST':
        form=EventForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('backend:event_calendar')
    else:
        form=EventForm()
    return render(request, 'backend/addevent.html', {'form':form})

@login_required(login_url='accounts/login/')
def eventdetail(request, id):
    context={
        'event':Event.objects.get(id=id)
    }
    return render(request, 'backend/eventdetail.html', context)

@login_required(login_url='accounts/login/')
def editevent(request, id):
    event=get_object_or_404(Event,id=id)
    form=EventForm(request.POST or None, instance=event)

    if form.is_valid():
        form.save()
        return redirect(reverse('backend:eventdetail', kwargs={"id":id}))
    return render(request, 'backend/editevent.html', {'form':form})

@login_required(login_url='accounts/login/')
def deleteevent(request, id):
    event=get_object_or_404(Event,id=id)
    event.delete()
    return render(request, 'backend/event_calendar.html')

backend/templates/backend/about.html
{%extends 'backend/base.html' %}

{% block title %}About CSS {%endblock%}

{% block content %}
       
    <p>This is the official website for Luther College Computer Science Society. It is a student ran organization.</p>

{%endblock%}

backend/templates/backend/addevent.html
{%extends 'backend/base.html' %}

{% block content %}

<div >
    <a href="{'% url 'backend:event_calendar' %}"> Calendar </a>
  </div>

    <form action="{% url 'backend:addevent' %}" method="POST">
      {% csrf_token %}
      <table>
      {{ form.as_table }}
      </table>
      <input type="submit" value="Submit">
    </form>
{%endblock%}

backend/templates/backend/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{% block title %}{% endblock %}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="{% static 'backend/style.css' %}">
</head>
<body class="d-flex flex-column min-vh-100">
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{%url 'backend:index' %}">LUTHER CSS</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{%url 'backend:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{%url 'backend:about' %}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{%url 'backend:roster' %}">Roster</a>
          </li>
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link active" href="{%url 'backend:event_calendar' %}">Event Calendar</a>
            </li>
          {% endif %}
        </ul>
        <ul class="nav navbar-nav navbar-right">
          {% if user.is_admin %}
          <li class="nav-item"><a class="nav-link active" href="{%url 'backend:createpost' %}">New Post</a></li>
          {% endif %}
          {% if not user.is_authenticated %}
          <li class="nav-item"><a class="nav-link active" href="{% url 'accounts:sign_up' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
          <li class="nav-item"><a class="nav-link active" href="{%url 'accounts:log_in' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
          {% endif %}
          {% if user.is_authenticated %}
          <li class="nav-item"><a class="nav-link active" href="{%url 'accounts:profile' %}">Profile</a></li>
          <li class="nav-item"><a class="nav-link active" href="{%url 'accounts:log_out' %}">Logout</a></li>
          {% endif %}
      </ul>


      </div>
    </div>
    </nav>
    <div class="postcontainer overflow-auto">
        {%block content %}
        {% endblock %}
    </div>

  <footer id="footer" class="mt-auto">

        © 2020 Copyright:Luther CSS

  
  </footer>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
</body>
</html>



























    

      

backend/templates/backend/editevent.html
{%extends 'backend/base.html' %}

{% block title %}Edit Event {%endblock%}

{% block content %}
       
<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Update">
  </form>

{%endblock%}

backend/templates/backend/editpost.html
{%extends 'backend/base.html' %}

{% block title %}Edit Post {%endblock%}

{% block content %}
       
<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Update">
  </form>

{%endblock%}

backend/templates/backend/event_calendar.html
{%extends 'backend/base.html' %}

{% block title %}Calendar {%endblock%}

{% block content %}
<div >
    <a href="{% url 'backend:addevent' %}"> Add Event </a>
</div>

<a href="{% url 'backend:event_calendar' %}?{{prev_month}}">Previous month</a>
<a href="{% url 'backend:event_calendar' %}?{{next_month}}">Next month</a>   

{{ calendar }}
{%endblock%}

backend/templates/backend/eventdetail.html
{%extends 'backend/base.html' %}

{% block title %}Event detail {%endblock%}

{% block content %}
<li>{{event.event_title}}--{{event.event_description}}--{{event.start_time}}--{{event.end_time}}</li>
<li><a href="{% url 'backend:editevent' event.id %}">Edit</a>
<li> <a href="{% url 'backend:deleteevent' event.id %}">Delete</a></li>    
{%endblock%}

backend/templates/backend/index.html
{%extends 'backend/base.html' %}

{% block content %}




        {% if posts %}
            {% for post in posts %}


            <div class="card">
                <div class="card-header">
                    <h2><a href="{% url 'backend:postdetail' post.id %}">{{post.post_title}}</a></h2>
                    <p class="card-title"><i class="fa fa-user"></i> by <a href="{%url 'accounts:profile' %}">{{post.author_id.first_name}}</a>
                        <i class="fa fa-calendar"></i> Posted on {{post.pub_date}} </p>
                </div>
                <div class="card-body">
                  
                  <p class="card-text">{{post.post_content}}</p>
                </div>
              </div>
            {% endfor %}


        {% else %}
            no posts.
        {% endif %}

{%endblock%}

backend/templates/backend/newpost.html
{%extends 'backend/base.html' %}

{% block content %}
    <form action="{% url 'backend:createpost' %}" method="POST">
      {% csrf_token %}
      <table>
      {{ form.as_table }}
      </table>
      <input type="submit" value="Submit">
    </form>
{%endblock%}

backend/templates/backend/postdetail.html
{%extends 'backend/base.html' %}

{% block title %}Post detail {%endblock%}

{% block content %}
<li>{{post.author_id.first_name}}--{{post.post_title}}--{{post.post_content}}--{{post.pub_date}}</li>
<li><a href="{% url 'backend:editpost' post.id %}">Edit</a>
<li> <a href="{% url 'backend:deletepost' post.id %}">Delete</a></li>    
{%endblock%}

backend/templates/backend/roster.html
{%extends 'backend/base.html' %}

{% block content %}
    {% if users %}
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th scope="col">First Name</th>
          <th scope="col">Last Name</th>
          <th scope="col">Email</th>
          <th scope="col">Year</th>
        </tr>
      </thead>
      <tbody>

        {% for user in users %}
        <tr>
            <td>{{user.first_name}}</td>
            <td>{{user.last_name}}</td>
            <td>{{user.email}}</td>
            <td>{{user.year}}</td>
        </tr>
        {% endfor %}
        
        
      </tbody>
    </table>






    {% else %}
        no posts.
    {% endif %}
{%endblock%}